remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Wie gross ist der Anteil der Heizöl-, Gas- und Elektrizitätsheizungen in einer Gemeinde?
